blank_issues_enabled: false
contact_links:
  - name: ⚠️ Provider Issue
    url: https://github.com/Flixclusive/flx-providers/issues
    about: If you have troubles with a provider or want to propose a new provider, please open an issue in the Flixclusive provider repository instead